#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f top.vcd

#run verilator to translate verilog into c++, including c++ testbench
verilator -Wall --cc --trace top.sv --exe riscs_tb.cpp

#build c++ porject viamake automatically generated by verilator 
make -j -C obj_dir/ -f Vtop.mk Vtop

#run executable simulation file 
echo -e "\nrunning simulation\n"
obj_dir/Vtop
echo -e "\\ncomplete simulation\n"

