#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f datapath.vcd

clear

#run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace datapath.sv --exe datapath_tb_v2.cpp
verilator -Wall --cc --trace data_memory.sv
verilator -Wall --cc --trace register_file.sv
verilator -Wall --cc --trace alu.sv

#build c++ project via make autormatically generated by Verilator
make -j -C obj_dir/ -f Vdatapath.mk Vdatapath

#run executable simulation file
obj_dir/Vdatapath