#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f alu_decoder.vcd

#run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace alu_decoder.sv --exe alu_decoder_tb.cpp

#build c++ project via make autormatically generated by Verilator
make -j -C obj_dir/ -f Valu_decoder.mk Valu_decoder

#run executable simulation file
obj_dir/Valu_decoder