#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f cache.vcd

#run verilator to translate verilog into c++, including c++ testbench
verilator -Wall --cc --trace cache.sv --exe cache_tb_v2.cpp

#build c++ porject viamake automatically generated by verilator 
make -j -C obj_dir/ -f Vcache.mk Vcache

#run executable simulation file 
obj_dir/Vcache
