#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f controlUnit_top.vcd

#run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace controlUnit_top.sv -Imain_decoder -Ialu_decoder --exe controlUnit_top_tb.cpp

#build c++ project via make autormatically generated by Verilator
make -j -C obj_dir/ -f VcontrolUnit_top.mk VcontrolUnit_top

#run executable simulation file
obj_dir/VcontrolUnit_top