#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f extend_unit.vcd

#run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace extend_unit.sv --exe extend_unit_tb.cpp

#build c++ project via make autormatically generated by Verilator
make -j -C obj_dir/ -f Vextend_unit.mk Vextend_unit

#run executable simulation file
obj_dir/Vextend_unit