#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f alu.vcd

#run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace alu.sv --exe alu_tb.cpp

#build c++ project via make autormatically generated by Verilator
make -j -C obj_dir/ -f Valu.mk Valu

#run executable simulation file
obj_dir/Valu