#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f instruction_memory.vcd

#run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace instruction_memory.sv --exe instruction_memory_tb.cpp

#build c++ project via make autormatically generated by Verilator
make -j -C obj_dir/ -f Vinstruction_memory.mk Vinstruction_memory

#run executable simulation file
obj_dir/Vinstruction_memory