#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f programcounter.vcd

# run Verilator to translate Verilog intro C++, including C++ testbench
verilator -Wall --cc --trace programcounter.sv --exe programcounter_tb.cpp

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vprogramcounter.mk Vprogramcounter

#run executable simulation file
obj_dir/Vprogramcounter