#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f main_decoder.vcd

#run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace main_decoder.sv --exe main_decoder_tb.cpp

#build c++ project via make autormatically generated by Verilator
make -j -C obj_dir/ -f Vmain_decoder.mk Vmain_decoder

#run executable simulation file
obj_dir/Vmain_decoder